slug: "sma_data_manager_bridge_addon"
version: "0.2.5"
name: "SMA Data Manager Bridge"
description: "SMA Data Manager Bridge"
url: "https://github.com/shadow578/ha-sma-solar-addons/tree/main/sma-data-manager-bridge"
init: false
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
  - i386
options:
  cooldown: 60
  debug_requests: false,
  no_http_error_codes: false
schema:
  cooldown: int
  debug_requests: bool
  no_http_error_codes: bool
