slug: "sma_data_manager_bridge_addon"
version: "0.2.0"
name: "SMA Data Manager Bridge"
description: "SMA Data Manager Bridge"
url: "https://github.com/shadow578/ha-sma-solar-addons/tree/main/sma-data-manager-bridge"
init: false
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
  - i386
